name: BountyTag
main: com.meloncraft.BountyTag.BountyTag
version: 1.0
commands:
   retag:
      description: recalculates the value of all players
      usage: /l
      permission: 
      permission-message: Test permission message
   bounty:
      description: Check the value of your inventory
      usage: /bounty
      permission: 
      permission-message: You don't have permission to use /bounty!